name: rz-svd

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            python3-wheel \
            python3-setuptools \
            python3-dev \
            meson \
            ninja-build \
            git

      - name: Clone Rizin
        run: |
          git clone --depth 1 https://github.com/rizinorg/rizin

      - name: Checkout rz-svd into Rizin subprojects
        uses: actions/checkout@v3
        with:
          path: rizin/subprojects/rz-svd

      - name: Build Rizin (with rz-svd subproject)
        run: |
          cd rizin
          meson setup build --buildtype=release --prefix=/usr 2>&1 | tee meson-output.txt
          grep 'rz-svd.*YES' meson-output.txt
          ninja -C build
          sudo ninja -C build install